default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  host: localhost
  port: 5432

production:
  <<: *default
  database: AppleProjProduction

test:
  <<: *default
  database: AppleProjTest

development:
  <<: *default
  database: AppleProjDevelopment